import React from 'react'
import NavigationText from '../../components/NavigationText/NavigationText'
import classes from './HouseInfo.module.css'
import PageInfoNavigation from './PageInfoNavigation/PageInfoNavigation'
import fonts from '../../globalCss/Fonts.module.css'
import Contact from '../Contact/Contact'
import Footer from '../../components/Footer/Footer'
import Header from '../../components/Header/Header'

class HouseInfo extends React.Component{
    state = {
        curIndex: 0,
        allImageNames: [
            "gallery-0.png","gallery-1.png","gallery-2.png","gallery-3.png",
            "gallery-4.png","gallery-5.png","gallery-6.png","gallery-7.png",
            "gallery-8.png","gallery-9.png","gallery-10.png","gallery-11.png",
            "gallery-12.png","gallery-13.png",
        ],
        loading: false
    }

    onClickSmallImageHandler = index => {
        this.setState({curIndex: index, loading: true})
        setTimeout(()=>this.setState({loading: false}), 300)
    }

    render(){
        return (
            <React.Fragment>
                <Header/>
                <NavigationText/>
                <div className={fonts.Title}>8600 BURNABY LAKE</div>
                <div className={classes.BigImage}
                    style={{
                        backgroundImage: "url('/images/PageInfoImages/" + this.state.allImageNames[this.state.curIndex] + "')",
                        opacity: this.state.loading ? "0" : "1"
                    }}>
                            
                </div>
                <PageInfoNavigation/>
                <div className={classes.SmallImageWrapper}>

                
                {this.state.allImageNames.map((imageName,index)=>(
                    <div className={classes.SmallImage}
                        key={index}
                        style={{
                            backgroundImage: "url('/images/PageInfoImages/" + imageName + "')"
                        }}
                        onClick={()=>this.onClickSmallImageHandler(index)}>

                    </div>
                ))}
                </div>
                <div className={classes.ContentWrapper}>
                Big, bright, updated 3-storey home in a fabulous block near Main Street. 3 updated
                 suites with 2 rented to great tenants. Lots of great options: perfect for owner occupiers 
                 who want to live in one and pay down the mortgage, a smart investor or convert back
                  to a single family home with 3 bedrooms up and a suite. Main floor has 2 bedrooms, high
                   ceilings, an updated kitchen & bath & opens to a fabulous deck & backyard oasis. Big 2
                    bedroom basement suite was completely redone in 2008 and the 1 bedroom top floor 
                    suite is adorable and ready to move in. Updated wiring, plumbing, roof - an excellent 
                    investment for the future.
                </div>
                <div className={classes.PriceInfo}>
                    <div className={classes.Price}>$ 1,798,000</div>
                    <table>
                        <tr>
                            <th className={classes.PropsHeader}>Properties Type</th><td>Residential Detached</td>
                        </tr>
                        <tr>
                            <th className={classes.PropsHeader}>MLS&reg; Number</th><td>R2452265</td>
                        </tr>
                        <tr>
                            <th className={classes.PropsHeader}>Status</th><td>Active</td>
                        </tr>
                        <tr>
                            <th className={classes.PropsHeader}>Bedrooms</th><td>3</td>
                        </tr>
                        <tr>
                            <th className={classes.PropsHeader}>Year Built</th><td>1990</td>
                        </tr>
                    </table>
                </div>
                <div className={classes.HouseDetail}>

                </div>
                <div className={classes.UpdateDateTxt}>Data was last updated May 3, 2020 at 05:10 PM (UTC)</div>
                <div className={classes.BtmTxt}>
                The data relating to real estate on this website comes in part from the MLS® Reciprocity program 
                of either the Real Estate Board of Greater Vancouver (REBGV), the Fraser Valley Real Estate Board
                 (FVREB) or the Chilliwack and District Real Estate Board (CADREB). Real estate listings held by 
                 participating real estate firms are marked with the MLS® logo and detailed information about the
                  listing includes the name of the listing agent. This representation is based in whole or part on
                   data generated by either the REBGV, the FVREB or the CADREB which assumes no responsibility for 
                   its accuracy. The materials contained on this page may not be reproduced without the express 
                   written consent of either the REBGV, the FVREB or the CADREB.
                </div>
                <Contact/>
                <Footer/>
            </React.Fragment>
        )
    }
    
}

export default HouseInfo